config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages_#home'

  get  'static_pages/home' => 'static_pages_#home'
  get  'static_pages/help' => 'static_pages_#help'
  get  'static_pages/user_home' => 'static_pages_#user_home'
  
  
  resources :keijibans
  
  post '/users/todos/:id/update' =>'todos#todo_update'
  
  get '/users/todos/:id/destroy' => 'todos#todo_destroy'
  
  get '/users/todos/:id/edit' => 'todos#todo_edit'
  
  get '/users/todos/:id' => 'todos#todo_detail'
  
  post '/users/todos/create' => 'todos#todo_create'
  
  post '/users/todos/create_universal' => 'todos#todo_create_universal'
  
  get '/users/:id' => 'users#todolist'
  
  post '/login' => 'users#login'
  
  post '/create' => 'users#create'
  
  get '/logout' => 'users#logout'
  
  get '/login_form' => 'users#login_form'
  
  get '/signup' => 'users#signup'

end

app/models/keijiban.rb
class Keijiban < ActiveRecord::Base
    belongs_to :user
    validates :content, length: { maximum: 500 }
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/todo.rb
class Todo < ActiveRecord::Base
    default_scope -> { order(deadline: :asc) }
end

app/models/twitter_app.rb
class TwitterApp < ActiveRecord::Base
  belongs_to :user
   validates :user_id, presence: true
end
   

app/models/user.rb
class User < ActiveRecord::Base
    has_many :keijibans
    has_many :microposts, dependent: :destroy
    def todos
        return Todo.where(user_id: self.id)
    end

    def todos_universal
        return Todo.where(universal: true)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def home
    @user = User.find_by(id:session[:user_id])
    if @user
      redirect_to("/users/#{@user.id}")
    else
      redirect_to("/signup")
    end
  end
  
  
end

app/controllers/keijibans_controller.rb
class KeijibansController < ApplicationController
  before_action :set_keijiban, only: [:show, :edit, :update, :destroy]

  # GET /keijibans
  # GET /keijibans.json
  def index
    @keijibans = Keijiban.all
  end

  # GET /keijibans/1
  # GET /keijibans/1.json
  def show
  end

  # GET /keijibans/new
  def new
    @keijiban = Keijiban.new
  end

  # GET /keijibans/1/edit
  def edit
  end

  # POST /keijibans
  # POST /keijibans.json
  def create
    @keijiban = Keijiban.new(keijiban_params)

    respond_to do |format|
      if @keijiban.save
        format.html { redirect_to @keijiban, notice: 'Keijiban was successfully created.' }
        format.json { render :show, status: :created, location: @keijiban }
      else
        format.html { render :new }
        format.json { render json: @keijiban.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keijibans/1
  # PATCH/PUT /keijibans/1.json
  def update
    respond_to do |format|
      if @keijiban.update(keijiban_params)
        format.html { redirect_to @keijiban, notice: 'Keijiban was successfully updated.' }
        format.json { render :show, status: :ok, location: @keijiban }
      else
        format.html { render :edit }
        format.json { render json: @keijiban.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keijibans/1
  # DELETE /keijibans/1.json
  def destroy
    @keijiban.destroy
    respond_to do |format|
      format.html { redirect_to keijibans_url, notice: 'Keijiban was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keijiban
      @keijiban = Keijiban.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keijiban_params
      params.require(:keijiban).permit(:content, :user_id)
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def user_home
  end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    
    def todo_create
        @user = User.find_by(id: session[:user_id])
        Todo.create(content: params[:content], user_id: @user.id, deadline: params[:deadline], title: params[:title])
        redirect_to("/users/#{@user.id}")
    end
    
    def todo_create_universal
        @user = User.find_by(id: session[:user_id])
        Todo.create(content: params[:content], universal: true, deadline: params[:deadline], title: params[:title])
        redirect_to("/users/#{@user.id}")
    end
    
    def todo_detail
        @todo = Todo.find_by(id: params[:id])
        @id = params[:id]
    end
    
    def todo_edit
        @todo = Todo.find_by(id: params[:id])
    end
    
    def todo_update
        @user = User.find_by(id: session[:user_id])
        @todo = Todo.find_by(id: params[:id])
        @todo.deadline = params[:deadline]
        @todo.title = params[:title]
        @todo.content = params[:content]
        @todo.save
        redirect_to("/users/#{@user.id}")
    end
    
    def todo_destroy
        @user = User.find_by(id: session[:user_id])
        @todo = Todo.find_by(id: params[:id])
        @todo.destroy
        redirect_to("/users/#{@user.id}")
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
  end
  
  def create
    @user = User.create(name: params[:name], email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Papa!"
      UserMailer.welcome_email(@user).deliver_later
      redirect_to("/users/#{@user.id}")
     else
      redirect_to :signup, :alert => "errorが起きました"
    end
  end
  
  def login_form
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      #UserMailer.welcome_email(@user).deliver_later
      redirect_to("/users/#{@user.id}")
    else
      redirect_to("/login_form")
      flash[:alert] = "Invalid email/password combination"
    end
  end
  
  def logout
    session[:user_id] = nil
    redirect_to("/login_form")
  end
  
  def todolist
    @user = User.find_by(id: params[:id])
    @id = params[:id]
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keijibans_helper.rb
module KeijibansHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/keijibans/_form.html.erb
<%= form_for(@keijiban) do |f| %>
  <% if @keijiban.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keijiban.errors.count, "error") %> prohibited this keijiban from being saved:</h2>

      <ul>
      <% @keijiban.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keijibans/edit.html.erb
<h1>Editing Keijiban</h1>

<%= render 'form' %>

<%= link_to 'Show', @keijiban %> |
<%= link_to 'Back', keijibans_path %>

app/views/keijibans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>掲示板</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keijibans.each do |keijiban| %>
      <tr>
        <td><%= keijiban.content %></td>
        <td><%= keijiban.user_id %></td>
        <td><%= link_to '表示', keijiban %></td>
        <td><%= link_to '変更', edit_keijiban_path(keijiban) %></td>
        <td><%= link_to '消去', keijiban, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keijiban', new_keijiban_path %>

app/views/keijibans/new.html.erb
<h1>New Keijiban</h1>

<%= render 'form' %>

<%= link_to 'Back', keijibans_path %>

app/views/keijibans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @keijiban.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @keijiban.user_id %>
</p>

<%= link_to 'Edit', edit_keijiban_path(@keijiban) %> |
<%= link_to 'Back', keijibans_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaPa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <h1>PAPA: Personal Assistant Parent Application</h1>
  <header>
    <% if session[:user_id] %>
      <% current_user = User.find_by(id: session[:user_id]) %>
      <i><%= link_to(current_user.name, "/users/#{current_user.id}") %></i>
      <%= link_to("keijiban", "/keijibans") %>
      <%= link_to("mytodos", "/todos") %>
      <%= link_to("myhome", "/static_pages/user_home") %>
      <%= link_to("logout", "/logout") %>
    <% else %>
      <%= link_to("signup", "/signup") %>
      <%= link_to("login", "/login_form") %>
      <%= link_to("keijiban", "/keijibans") %>
      <%= link_to("home", "/static_pages/home") %>
      <%= link_to("mytodos", "/todos") %> 
    <% end %>
  </header>

<body>

<%= yield %>

</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> This is the Papa web application for education</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      Please <a "https://login-3-yonakahara.c9users.io/login_form"><em>login</em></a> to access your todos, notices and to message people.<br>
      This is an web application for middle and high school students of Nishiyamato Gakuen High School in Nara, Japan.<br>
      Made as part of 未踏ジュニア２０１７
    </p>
  </body>
</html>

app/views/static_pages/user_home.html.erb
<h1>StaticPages#user_home</h1>
<p>Find me in app/views/static_pages/user_home.html.erb</p>

app/views/todos/todo_detail.html.erb
<h3>Todo Detail</h3>

<%= @todo.title %>

</br>

<%= @todo.content %>

</br>

<%= link_to("Edit", "/users/todos/#{@todo.id}/edit") %>

</br>

<%= link_to("Delete", "/users/todos/#{@todo.id}/destroy") %>

app/views/todos/todo_edit.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
</head>

<h3>Todo Edit</h3>

<%= form_tag("/users/todos/#{@todo.id}/update") do %>

    <b>Deadline</b>
    
    </br>
    
    <input style="text" name="deadline" id="datepicker" value="<%= @todo.deadline %>" >
    
    </br>

    <b>Title</b>
    
    </br>

    <textarea name="title"><%= @todo.title %></textarea>
    
    </br>
    
    <b>Content</b>
    
    </br>

    <textarea name="content"><%= @todo.content %></textarea>
    
    </br>
    
    <input type="submit" value="save" >
    
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/login_form.html.erb
<head>
    <link rel="stylesheet" type="text/scss" href="users.scss">
</head>
<h3>Login</h3>

<b><%= flash[:alert] %></b>

<%= form_tag("/login") do %>

    <div>Email</div>    
    
        <input name="email">

    <div>Password</div>
    
        <input name="password" type="password">
        
    <input type="submit" value="login">
    
<% end %>

app/views/users/signup.html.erb
<h3>Signup</h3>

<%= form_tag("/create") do %>

    <div>Your Name</div>

        <input name="name">
        
    <div>Email</div>    
    
        <input name="email">

    <div>Password</div>
    
        <input name="password" type="password">
        
    <input type="submit" value="signup">
    
<% end %>

app/views/users/todolist.html.erb
<h3>TodoList</h3>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
</head>

<body>
    
    <div><b>From Teacher</b></div>
    
    <% @user = User.find_by(id: session[:user_id]) %>

    <% @user.todos_universal.each do |todo| %>
    
        <%= todo.deadline %>
        
        <li><input type="checkbox"><b><%= link_to(todo.title, "/users/todos/#{todo.id}") %></b></li>
    
    <% end %>
    
    </br>
    
    <% if session[:user_id] == 1 %>
    
    <% else %>
    
        <div><b>Yours</b></div>
    
            <% @user.todos.each do |todo| %>
            
            <%= todo.deadline %>
    
            <li><input type="checkbox"><%= link_to(todo.title, "/users/todos/#{todo.id}") %></li>
        
        <% end %>
        
    <% end %>
    
    </br>
    
    <% if session[:user_id] == 1 %>
    
        <div><b>Universal Todo</b></div>
    
        <%= form_tag("/users/todos/create_universal") do %>
            <div>Deadline</div>
            <input type="text" id="datepicker" name="deadline">
            </br>
            <div>Titile</div>
            <input name="title">
            </br>
            <div>Content</div>
            <textarea name="content"></textarea>
            <input type="submit" value="confirm">
        <% end %>
        
    <% else %>
    
        <div><b>Add New Todo</b></div>
    
        <%= form_tag("/users/todos/create") do %>
            <div>Deadline</div>
            <input type="text" id="datepicker" name="deadline">
            </br>
            <div>Titile</div>
            <input name="title">
            </br>
            <div>Content</div>
            <textarea name="content"></textarea>
            <input type="submit" value="confirm">
        <% end %>
    
    <% end %>
    
</body>